// <auto-generated />
using System;
using Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180815125321_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Inventory.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ExpiryDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Type");

                    b.Property<int>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, ExpiryDate = new DateTime(2018, 8, 16, 12, 53, 21, 773, DateTimeKind.Utc), Name = "Apple", Type = "Food", WarehouseId = 1 },
                        new { Id = 2, ExpiryDate = new DateTime(2018, 8, 17, 12, 53, 21, 773, DateTimeKind.Utc), Name = "Banana", Type = "Food", WarehouseId = 1 },
                        new { Id = 3, ExpiryDate = new DateTime(2018, 8, 15, 12, 53, 21, 773, DateTimeKind.Utc), Name = "Milk", Type = "Food", WarehouseId = 1 },
                        new { Id = 4, ExpiryDate = new DateTime(2018, 8, 15, 12, 53, 21, 773, DateTimeKind.Utc), Name = "Meat", Type = "Food", WarehouseId = 1 },
                        new { Id = 5, ExpiryDate = new DateTime(2018, 8, 15, 12, 53, 21, 773, DateTimeKind.Utc), Name = "Bread", Type = "Food", WarehouseId = 1 }
                    );
                });

            modelBuilder.Entity("Inventory.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new { Id = 1, Name = "Main" }
                    );
                });

            modelBuilder.Entity("Inventory.Models.Product", b =>
                {
                    b.HasOne("Inventory.Models.Warehouse", "Warehouse")
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
